use_frameworks!
platform :ios, '16.0'

target 'CachingPlayerItem_Example' do
  pod 'CachingPlayerItem', :path => '../'

  target 'CachingPlayerItem_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 7.6.2'
    pod 'Nimble', '~> 13.8.0'
  end
end
